language: node_js
node_js: lts/*
cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.19.1
  - export PATH="$HOME/.yarn/bin:$PATH"

install: yarn

script: yarn build

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: vidflow-s3
    region: ap-northeast-2
    skip_cleanup: true
    acl: public_read
    local_dir: build
    wait-until-deployed: true
    on:
      repo: ryrie/vidflow-web
      branch: master

